# Generated by Django 5.2.2 on 2025-06-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_comment_author_id_remove_post_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='request_id',
            new_name='category_request',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_name',
        ),
    ]
